### PR TITLE
Removes simgui json files and edits git ignore slightly

### PR DESCRIPTION
**Pull request by redguy999**
makes it so that the simgui json files are no longer tracked.

### CODE REVIEW

**Comment by alexandersondev** [comment]
Will end up cleaning the entire folder instead

**Comment by alexandersondev** [comment]
*Deleting the entire folder

**Comment by redguy999** [comment]
This merge deletes the simgui json files in the root of the code, not the ones you deleted.

**Review by alexandersondev — APPROVED** [review]
Deletes the correct files and adds the correct git ignore
They are local to each machine so this is best practice

**Pull request merged**
