### PR TITLE
Merges LED into main

### PR DESCRIPTION
**Pull request by redguy999**
I'll go figure out how to fix merge conflicts, somehow.

### CODE REVIEW

**Comment by alexandersondev** [comment]
There are conflicts that need to be resolved

**Comment by alexandersondev** [comment]
There are conflicts here, perhaps we should wait for merging LED until the LED is on the robot?

**Comment by redguy999** [comment]
> There are conflicts that need to be resolved

Thought I fixed them earlier, I'm go check.

**Comment by redguy999** [comment]
Now its good.

**Comment by redguy999** [comment]
I won't fix the conflicts until we merge new_intake into main.

**Comment by redguy999** [comment]
Closing this and making a new one.

**Pull request closed without merging**
